gemfile:
  - gemfiles/Gemfile.rails-4.1.x
  - gemfiles/Gemfile.rails-5.0.x
  - gemfiles/Gemfile.rails-5.1.x
rvm:
  - 2.4.5
  - 2.5.1
cache: bundler
sudo: false
env:
  global:
  - AWS_REGION=eu-central-1
