# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: conveyor_belt 1.0.0 ruby lib

Gem::Specification.new do |s|
  s.name = "conveyor_belt"
  s.version = "1.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Julik Tarkhanov"]
  s.date = "2016-01-16"
  s.description = "Process jobs from SQS"
  s.email = "me@julik.nl"
  s.extra_rdoc_files = [
    "README.md"
  ]
  s.files = [
    ".gitlab-ci.yml",
    "DETAILS.md",
    "FAQ.md",
    "Gemfile",
    "README.md",
    "Rakefile",
    "example.env",
    "lib/conveyor_belt.rb",
    "lib/conveyor_belt/atomic_counter.rb",
    "lib/conveyor_belt/cli.rb",
    "lib/conveyor_belt/connection.rb",
    "lib/conveyor_belt/contrib/appsignal_wrapper.rb",
    "lib/conveyor_belt/contrib/performable.rb",
    "lib/conveyor_belt/execution_context.rb",
    "lib/conveyor_belt/middleware_stack.rb",
    "lib/conveyor_belt/null_logger.rb",
    "lib/conveyor_belt/serializer.rb",
    "lib/conveyor_belt/simple_job.rb",
    "lib/conveyor_belt/submitter.rb",
    "lib/conveyor_belt/version.rb",
    "lib/conveyor_belt/worker.rb",
    "spec/conveyor_belt/atomic_counter_spec.rb",
    "spec/conveyor_belt/cli_app.rb",
    "spec/conveyor_belt/cli_spec.rb",
    "spec/conveyor_belt/connection_spec.rb",
    "spec/conveyor_belt/execution_context_spec.rb",
    "spec/conveyor_belt/middleware_stack_spec.rb",
    "spec/conveyor_belt/serializer_spec.rb",
    "spec/conveyor_belt/simple_job_spec.rb",
    "spec/conveyor_belt/submitter_spec.rb",
    "spec/conveyor_belt/worker_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = "https://gitlab.wetransfer.net/julik/conveyor_belt"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.2.2"
  s.summary = "A full-featured library for all them worker needs"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<aws-sdk>, ["~> 2"])
      s.add_runtime_dependency(%q<ks>, [">= 0"])
      s.add_runtime_dependency(%q<very_tiny_state_machine>, ["~> 1"])
      s.add_runtime_dependency(%q<hash_tools>, [">= 0"])
      s.add_development_dependency(%q<dotenv>, [">= 0"])
      s.add_development_dependency(%q<rake>, [">= 0"])
      s.add_development_dependency(%q<rspec>, ["~> 3.2.0"])
      s.add_development_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 2.0.1"])
    else
      s.add_dependency(%q<aws-sdk>, ["~> 2"])
      s.add_dependency(%q<ks>, [">= 0"])
      s.add_dependency(%q<very_tiny_state_machine>, ["~> 1"])
      s.add_dependency(%q<hash_tools>, [">= 0"])
      s.add_dependency(%q<dotenv>, [">= 0"])
      s.add_dependency(%q<rake>, [">= 0"])
      s.add_dependency(%q<rspec>, ["~> 3.2.0"])
      s.add_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_dependency(%q<bundler>, ["~> 1.0"])
      s.add_dependency(%q<jeweler>, ["~> 2.0.1"])
    end
  else
    s.add_dependency(%q<aws-sdk>, ["~> 2"])
    s.add_dependency(%q<ks>, [">= 0"])
    s.add_dependency(%q<very_tiny_state_machine>, ["~> 1"])
    s.add_dependency(%q<hash_tools>, [">= 0"])
    s.add_dependency(%q<dotenv>, [">= 0"])
    s.add_dependency(%q<rake>, [">= 0"])
    s.add_dependency(%q<rspec>, ["~> 3.2.0"])
    s.add_dependency(%q<rdoc>, ["~> 3.12"])
    s.add_dependency(%q<bundler>, ["~> 1.0"])
    s.add_dependency(%q<jeweler>, ["~> 2.0.1"])
  end
end

