name: Ruby

on: [push, pull_request]

jobs:
  build:
    name: Ruby ${{ matrix.ruby }}, Gemfile ${{ matrix.gemfile }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby:
          - 3.2
          - 3.1
          - 3.0
        gemfile:
          - gemfiles/Gemfile.rails-6.1.x
          - gemfiles/Gemfile.rails-7.0.x
    env:
      SQS_QUEUE_URL: 'sqlite3://tmp/sqewer.sqlite3'
      AWS_REGION: 'eu-central-1'
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
    - name: install gems
      run: |
        gem install sqlite3
        gem install bundler
        bundle install --gemfile ${{ matrix.gemfile }}
    - name: Tests
      run: |
        bundle exec rspec --tag "~sqs"
